# Generated by Django 2.2.7 on 2019-12-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='keyword',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
