# Generated by Django 2.2.7 on 2019-12-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191202_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id']},
        ),
    ]
