# Generated by Django 2.2.7 on 2019-12-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20191202_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id'], 'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
    ]
