# Generated by Django 2.2.7 on 2019-12-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20191203_1056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='t_ff_news',
        ),
    ]
