# Generated by Django 2.2.7 on 2019-12-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191203_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='savedate',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
