# Generated by Django 2.2.7 on 2019-12-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windcode', models.CharField(max_length=8, unique=True)),
                ('category', models.IntegerField(choices=[(1, 'public'), (2, 'private'), (3, 'wealth')])),
            ],
        ),
    ]
