# Generated by Django 2.2.7 on 2019-12-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='category',
            field=models.IntegerField(choices=[(1, '公募基金'), (2, '私募基金'), (3, '银行理财')], verbose_name='证券类别'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='windcode',
            field=models.CharField(max_length=12, unique=True, verbose_name='证券代码'),
        ),
        migrations.CreateModel(
            name='FundNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.FloatField(null=True, verbose_name='净值')),
                ('nav_adj', models.FloatField(null=True, verbose_name='复权净值')),
                ('date', models.DateField(verbose_name='净值日期')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
        ),
    ]
