# Generated by Django 2.2.7 on 2019-12-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191203_1137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basicinfo',
            table='t_ff_basic_info',
        ),
        migrations.AlterModelTable(
            name='fund',
            table='t_ff_fund',
        ),
        migrations.AlterModelTable(
            name='fundnav',
            table='t_ff_fund_nav',
        ),
    ]
