# Generated by Django 2.2.7 on 2019-12-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191203_1140'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fund',
            table='t_ff_funds',
        ),
    ]
