# Generated by Django 2.2.7 on 2019-12-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191203_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='windcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode'),
        ),
    ]
