# Generated by Django 2.2.7 on 2019-12-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191203_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_fundmanager', models.CharField(max_length=20, verbose_name='基金经理')),
                ('fund_predfundmanager', models.TextField(null=True, verbose_name='历任基金经理')),
                ('fund_corp_fundmanagementcompany', models.CharField(max_length=20, verbose_name='管理人')),
                ('update_date', models.DateField(verbose_name='更新日期')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode', unique=True)),
            ],
            options={
                'verbose_name': '基金经理',
                'verbose_name_plural': '基金经理',
                'db_table': 't_ff_manager',
            },
        ),
        migrations.CreateModel(
            name='ManagerExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_manager_totalnetasset', models.FloatField(verbose_name='管理规模')),
                ('fund_manager_resume', models.TextField(verbose_name='简介')),
                ('fund_manager_gender', models.CharField(max_length=2, verbose_name='性别')),
                ('nav_periodicannualizedreturn', models.FloatField(verbose_name='年化收益')),
                ('rank', models.IntegerField(verbose_name='顺序')),
                ('update_date', models.DateField(verbose_name='更新日期')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Manager', to_field='windcode')),
            ],
            options={
                'verbose_name': '基金经理-扩展数据',
                'verbose_name_plural': '基金经理-扩展数据',
                'db_table': 't_ff_manager_expand',
            },
        ),
        migrations.CreateModel(
            name='IndicatorForPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_setupdate', models.DateField(verbose_name='成立日期')),
                ('fund_corp_fundmanagementcompany', models.CharField(max_length=25, verbose_name='管理人')),
                ('fund_fundscale', models.FloatField(verbose_name='规模')),
                ('prt_netasset', models.FloatField(verbose_name='净资产')),
                ('rpt_date', models.DateField(verbose_name='报告期')),
                ('update_date', models.DateField(verbose_name='更新日期')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '画图用数据',
                'verbose_name_plural': '画图用数据',
                'db_table': 't_ff_indicator_for_plot',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=50, verbose_name='指标名称')),
                ('numeric', models.FloatField(null=True)),
                ('text', models.TextField(null=True)),
                ('note', models.CharField(max_length=2)),
                ('rpt_date', models.DateField(verbose_name='报告期')),
                ('update_date', models.DateField(verbose_name='更新日期')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '筛选用数据',
                'verbose_name_plural': '筛选用数据',
                'db_table': 't_ff_indicator_for_filter',
            },
        ),
    ]
