# Generated by Django 2.2.7 on 2019-12-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_indicator_indicatorforplot_manager_managerextend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='windcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode'),
        ),
    ]
