# Generated by Django 2.2.7 on 2019-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191203_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='note',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
