# Generated by Django 2.2.7 on 2019-12-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191203_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicInfo',
        ),
    ]
