# Generated by Django 2.2.7 on 2019-12-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191203_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='benchmark',
            field=models.TextField(db_column='fund_benchmark', null=True, verbose_name='业绩基准'),
        ),
    ]
