# Generated by Django 2.2.7 on 2019-12-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191203_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windcode', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='指数简称')),
                ('sec_name', models.CharField(max_length=45, verbose_name='指数简称')),
                ('launch_date', models.DateField()),
                ('kind', models.CharField(default='normal', max_length=20)),
            ],
            options={
                'verbose_name': '指数列表',
                'verbose_name_plural': '指数列表',
                'db_table': 't_ff_index',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_id', models.IntegerField(auto_created=True, db_index=True, unique=True, verbose_name='组合ID')),
                ('port_name', models.CharField(max_length=30, verbose_name='组合名称')),
                ('port_type', models.IntegerField(choices=[(1, '普通组合')], verbose_name='组合类型')),
            ],
            options={
                'verbose_name': '基金池',
                'verbose_name_plural': '基金池',
                'db_table': 't_ff_portfolio',
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=12, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=12, verbose_name='股票简称')),
                ('rank', models.IntegerField(verbose_name='排序')),
                ('ratio', models.FloatField(verbose_name='占比')),
                ('change', models.FloatField(null=True, verbose_name='变化')),
                ('date', models.DateField(verbose_name='更新时间')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '股票配置',
                'verbose_name_plural': '股票配置',
                'db_table': 't_ff_asset_stock',
            },
        ),
        migrations.CreateModel(
            name='PortfolioObserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windcode', models.CharField(max_length=12, verbose_name='证券代码')),
                ('update_date', models.DateField(verbose_name='更新日期')),
                ('port_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Portfolio', to_field='port_id')),
            ],
            options={
                'verbose_name': '观察池',
                'verbose_name_plural': '观察池',
                'db_table': 't_ff_portfolio_observe',
            },
        ),
        migrations.CreateModel(
            name='PortfolioCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windcode', models.CharField(max_length=12, verbose_name='证券代码')),
                ('update_date', models.DateField(verbose_name='更新日期')),
                ('port_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Portfolio', to_field='port_id')),
            ],
            options={
                'verbose_name': '核心池',
                'verbose_name_plural': '核心池',
                'db_table': 't_ff_portfolio_core',
            },
        ),
        migrations.CreateModel(
            name='IndexClosePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.FloatField()),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Index', to_field='windcode')),
            ],
            options={
                'verbose_name': '指数收盘数据',
                'verbose_name_plural': '指数收盘数据',
                'db_table': 't_ff_index_cp',
            },
        ),
        migrations.CreateModel(
            name='FundPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=20, verbose_name='指标名称')),
                ('value', models.FloatField(null=True)),
                ('update_date', models.DateField(verbose_name='更新日期')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '基金近期表现',
                'verbose_name_plural': '基金近期表现',
                'db_table': 't_ff_performance',
            },
        ),
        migrations.CreateModel(
            name='Brinson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_code', models.CharField(max_length=2, null=True, verbose_name='行业代码')),
                ('industry_name', models.CharField(max_length=4, null=True, verbose_name='行业简称')),
                ('q1', models.FloatField(null=True)),
                ('q2', models.FloatField(null=True)),
                ('q3', models.FloatField(null=True)),
                ('q4', models.FloatField(null=True)),
                ('raa', models.FloatField(null=True)),
                ('rss', models.FloatField(null=True)),
                ('rin', models.FloatField(null=True)),
                ('rto', models.FloatField(null=True)),
                ('freq', models.CharField(default='S', max_length=2, verbose_name='单期/多期')),
                ('benchmark', models.CharField(max_length=12)),
                ('rpt_date', models.DateField(verbose_name='报告期')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '业绩归因(Brinson)',
                'verbose_name_plural': '业绩归因(Brinson)',
                'db_table': 't_ff_brinson',
            },
        ),
        migrations.CreateModel(
            name='BondHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_code', models.CharField(max_length=12, verbose_name='股票代码')),
                ('bond_name', models.CharField(max_length=12, verbose_name='股票简称')),
                ('rank', models.IntegerField(verbose_name='排序')),
                ('ratio', models.FloatField(verbose_name='占比')),
                ('change', models.FloatField(null=True, verbose_name='变化')),
                ('date', models.DateField(verbose_name='更新时间')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '股票配置',
                'verbose_name_plural': '股票配置',
                'db_table': 't_ff_asset_bond',
            },
        ),
        migrations.CreateModel(
            name='AssetIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=4, verbose_name='行业名称')),
                ('rank', models.IntegerField(verbose_name='排序')),
                ('ratio', models.FloatField(verbose_name='占比')),
                ('change', models.FloatField(null=True, verbose_name='变化')),
                ('date', models.DateField(verbose_name='更新时间')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '行业配置',
                'verbose_name_plural': '行业配置',
                'db_table': 't_ff_asset_industry',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.FloatField(default=0.0, verbose_name='股票')),
                ('bond', models.FloatField(default=0.0, verbose_name='债券')),
                ('fund', models.FloatField(default=0.0, verbose_name='基金')),
                ('warrant', models.FloatField(default=0.0, verbose_name='权证')),
                ('cash', models.FloatField(default=0.0, verbose_name='现金')),
                ('other', models.FloatField(default=0.0, verbose_name='其他')),
                ('date', models.DateField(verbose_name='更新时间')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '资产配置',
                'verbose_name_plural': '资产配置',
                'db_table': 't_ff_asset',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_value', models.FloatField()),
                ('small_growth', models.FloatField()),
                ('mid_value', models.FloatField()),
                ('mid_growth', models.FloatField()),
                ('large_value', models.FloatField()),
                ('large_growth', models.FloatField()),
                ('bond', models.FloatField()),
                ('value_date', models.DateField()),
                ('freq', models.CharField(max_length=2)),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '风格分析',
                'verbose_name_plural': '风格分析',
                'db_table': 't_ff_style',
                'index_together': {('value_date', 'windcode')},
            },
        ),
    ]
