# Generated by Django 2.2.7 on 2019-12-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_asset_assetindustry_bondholding_brinson_fundperformance_index_indexcloseprice_portfolio_portfoliocor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondholding',
            name='bond_code',
            field=models.CharField(max_length=12, verbose_name='债券代码'),
        ),
        migrations.AlterField(
            model_name='bondholding',
            name='bond_name',
            field=models.CharField(max_length=20, verbose_name='债券简称'),
        ),
    ]
