# Generated by Django 2.2.7 on 2019-12-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191204_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondholding',
            name='bond_code',
            field=models.CharField(max_length=18, verbose_name='债券代码'),
        ),
    ]
