# Generated by Django 2.2.7 on 2019-12-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191204_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='r_square',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
