# Generated by Django 2.2.7 on 2019-12-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_style_r_square'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'ordering': ['id'], 'verbose_name': '基金基础信息', 'verbose_name_plural': '基金基础信息'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['id'], 'verbose_name': '筛选用数据', 'verbose_name_plural': '筛选用数据'},
        ),
        migrations.CreateModel(
            name='IndicatorIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=50, verbose_name='指标名称')),
                ('numeric', models.FloatField(null=True)),
                ('text', models.TextField(null=True)),
                ('note', models.CharField(max_length=2, null=True)),
                ('rpt_date', models.DateField(verbose_name='报告期')),
                ('update_date', models.DateField(verbose_name='更新日期')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Index', to_field='windcode')),
            ],
            options={
                'verbose_name': '指数筛选用数据',
                'verbose_name_plural': '指数筛选用数据',
                'db_table': 't_ff_indicator_for_filter_index',
                'ordering': ['id'],
            },
        ),
    ]
