# Generated by Django 2.2.7 on 2019-12-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20191204_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorindex',
            name='note',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorindex',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
