# Generated by Django 2.2.7 on 2019-12-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191205_1732'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='indexcloseprice',
            index_together={('windcode', 'date')},
        ),
    ]
