# Generated by Django 2.2.7 on 2019-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20191210_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='windcode',
            field=models.CharField(max_length=20, unique=True, verbose_name='证券代码'),
        ),
        migrations.AlterField(
            model_name='index',
            name='windcode',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='指数简称'),
        ),
    ]
