# Generated by Django 2.2.7 on 2019-12-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20191211_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('company', models.CharField(max_length=100, null=True, verbose_name='管理人')),
                ('invest_type', models.CharField(max_length=20, verbose_name='投资策略')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic', to='api.Fund', to_field='windcode', unique=True)),
            ],
            options={
                'verbose_name': '产品基本信息表',
                'verbose_name_plural': '产品基本信息表',
                'db_table': 't_ff_basic',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='标签')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='api.Basic', to_field='windcode')),
            ],
            options={
                'verbose_name': '产品标签',
                'verbose_name_plural': '产品标签',
                'db_table': 't_ff_basic_label',
                'ordering': ['id'],
            },
        ),
    ]
