# Generated by Django 2.2.7 on 2019-12-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20191218_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.FloatField(default=0, verbose_name='短期利率债')),
                ('long', models.FloatField(default=0, verbose_name='长期利率债')),
                ('conver', models.FloatField(default=0, verbose_name='可转债')),
                ('cre_short', models.FloatField(default=0, verbose_name='短期信用债')),
                ('cre_medium', models.FloatField(default=0, verbose_name='中期信用债')),
                ('cre_long', models.FloatField(default=0, verbose_name='长期信用债')),
                ('interest', models.FloatField(default=0, verbose_name='质押式回购')),
                ('value_date', models.DateField()),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '债券型基金风格分析',
                'verbose_name_plural': '债券型基金风格分析',
                'db_table': 't_ff_style_bond',
                'index_together': {('value_date', 'windcode')},
            },
        ),
    ]
