# Generated by Django 2.2.7 on 2019-12-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_bondstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windcode', models.CharField(max_length=10, unique=True, verbose_name='证券代码')),
            ],
            options={
                'verbose_name': '股票列表',
                'verbose_name_plural': '股票列表',
                'db_table': 't_ff_stocks',
            },
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('beta', models.FloatField(verbose_name='BETA')),
                ('momentum', models.FloatField(verbose_name='动量')),
                ('size', models.FloatField(verbose_name='市值')),
                ('earning_yield', models.FloatField(verbose_name='盈利能力')),
                ('residual_volatility', models.FloatField(verbose_name='残差波动率')),
                ('growth', models.FloatField(verbose_name='成长')),
                ('book_to_price', models.FloatField(verbose_name='账面市值比')),
                ('leverage', models.FloatField(verbose_name='杠杆')),
                ('liquidity', models.FloatField(verbose_name='流动性')),
                ('nl_size', models.FloatField(verbose_name='非线性市值')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Stock', to_field='windcode')),
            ],
            options={
                'verbose_name': '风格因子-因子暴露',
                'verbose_name_plural': '风格因子-因子暴露',
                'db_table': 't_ff_barra_exposure',
                'index_together': {('date', 'windcode')},
            },
        ),
    ]
