# Generated by Django 3.0 on 2020-01-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_exposure_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='kind',
            field=models.CharField(default='normal', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='index',
            name='launch_date',
            field=models.DateField(verbose_name='成立日期'),
        ),
        migrations.AlterField(
            model_name='indicatorindex',
            name='numeric',
            field=models.FloatField(null=True, verbose_name='数值'),
        ),
        migrations.AlterField(
            model_name='indicatorindex',
            name='windcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Index', to_field='windcode', verbose_name='证券代码'),
        ),
        migrations.CreateModel(
            name='PortfolioExpand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_type', models.IntegerField(choices=[(1, '观察池'), (2, '核心池'), (3, '备投池')], verbose_name='组合类型')),
                ('windcode', models.CharField(max_length=12, verbose_name='证券代码')),
                ('update_date', models.DateField(verbose_name='更新日期')),
                ('port_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Portfolio', to_field='port_id')),
            ],
            options={
                'verbose_name': '基金池',
                'verbose_name_plural': '基金池',
                'db_table': 't_ff_portfolio_expand',
            },
        ),
    ]
