# Generated by Django 3.0 on 2020-01-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200114_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='comment',
            field=models.TextField(null=True, verbose_name='基金评价'),
        ),
    ]
