# Generated by Django 3.0 on 2020-02-28 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_basic_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundnav',
            name='revised_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='修正日期'),
            preserve_default=False,
        ),
    ]
