# Generated by Django 3.0 on 2020-03-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_fundnav_revised_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioobserve',
            name='port_id',
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': '基金池基础信息', 'verbose_name_plural': '基金池基础信息'},
        ),
        migrations.AlterModelOptions(
            name='portfolioexpand',
            options={'verbose_name': '基金池扩展信息', 'verbose_name_plural': '基金池扩展信息'},
        ),
        migrations.AddField(
            model_name='basic',
            name='manager',
            field=models.CharField(max_length=10, null=True, verbose_name='基金经理'),
        ),
        migrations.AddField(
            model_name='basic',
            name='scale',
            field=models.CharField(max_length=30, null=True, verbose_name='基金规模'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='windcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='category',
            field=models.IntegerField(choices=[(1, '公募基金'), (2, '私募基金'), (3, '银行理财'), (4, '券商资管')], verbose_name='证券类别'),
        ),
        migrations.AlterField(
            model_name='index',
            name='windcode',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='指数代码'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='note',
            field=models.CharField(max_length=2, null=True, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='numeric',
            field=models.FloatField(null=True, verbose_name='数值'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='text',
            field=models.TextField(null=True, verbose_name='文本数据'),
        ),
        migrations.AlterField(
            model_name='indicatorindex',
            name='note',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='indicatorindex',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='文本数据'),
        ),
        migrations.DeleteModel(
            name='PortfolioCore',
        ),
        migrations.DeleteModel(
            name='PortfolioObserve',
        ),
    ]
