# Generated by Django 3.0 on 2020-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200312_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(default='value', max_length=8, verbose_name='数据类型'),
            preserve_default=False,
        ),
    ]
