# Generated by Django 3.0 on 2020-03-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200313_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetindustry',
            name='update_date',
            field=models.DateField(default='2020-01-31', verbose_name='更新时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetindustry',
            name='date',
            field=models.DateField(verbose_name='报告期'),
        ),
    ]
