# Generated by Django 3.0 on 2020-04-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_fundnavall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundnav',
            options={'verbose_name': '基金净值-复权', 'verbose_name_plural': '基金净值-复权'},
        ),
        migrations.AddField(
            model_name='classify',
            name='kind',
            field=models.CharField(default='normal', max_length=20, verbose_name='类型'),
        ),
    ]
