# Generated by Django 2.2.7 on 2020-04-15 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20200414_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.AddField(
            model_name='asset',
            name='update_date',
            field=models.DateField(default=datetime.date(2020, 4, 15), verbose_name='更新时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(verbose_name='报告期'),
        ),
    ]
