# Generated by Django 3.0.3 on 2020-04-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_classify_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundnav',
            options={'verbose_name': '基金净值-复权', 'verbose_name_plural': '基金净值-复权'},
        ),
        migrations.CreateModel(
            name='FundNavAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nv', models.FloatField(null=True, verbose_name='净资产值(元)')),
                ('nav', models.FloatField(null=True, verbose_name='单位净值')),
                ('nav_acc', models.FloatField(null=True, verbose_name='累计单位净值')),
                ('daily_profit', models.FloatField(null=True, verbose_name='万份收益')),
                ('weekly', models.FloatField(null=True, verbose_name='七日年化')),
                ('date', models.DateField(verbose_name='净值日期')),
                ('windcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fund', to_field='windcode')),
            ],
            options={
                'verbose_name': '基金净值-全部',
                'verbose_name_plural': '基金净值-全部',
                'db_table': 't_ff_fund_nav_all',
                'index_together': {('windcode', 'date')},
            },
        ),
    ]
