# Generated by Django 3.0.3 on 2020-04-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20200414_1123'),
        ('api', '0043_auto_20200409_1620'),
    ]

    operations = [
    ]
