# Generated by Django 3.0.3 on 2020-04-15 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_merge_20200415_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='update_date',
            field=models.DateField(default=datetime.date(2020, 2, 29), verbose_name='更新时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(verbose_name='报告期'),
        ),
    ]
