# Generated by Django 3.0.3 on 2020-04-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20200415_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
    ]
