from api.views.search import *
from api.views.plot import *
from api.views.summary import *
from api.views.filter import *
from api.views.info import *
from api.views.manager import *
from api.views.attribution import *
from api.views.assetallocate import *
from api.views.portfolio import *
from api.views.nav_private import *
from api.views.benchmark import *
from api.views.compare import *
